modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "mahoutetra"
version = "${version}"
displayName = "MahouTetra"
# logoFile="icon.png" #optional
# authors="Me!" #optional
description = '''
MahouTetra
'''

[[dependencies.mahoutetra]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mahoutetra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
